#!/usr/bin/env bash

_opentoolbar_completion() {
    local cur prev
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    
    case "${prev}" in
        conservation-mode|usb-charging|touchpad|fn-lock)
            local opts="0 1 false true enable disable"
            COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
            return 0
            ;;
        *)
            ;;
    esac

    # Default completions
    local opts="conservation-mode usb-charging touchpad fn-lock -s --status -v --version -h --help"
    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    return 0
}

complete -F _opentoolbar_completion opentoolbar
